typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done


HELPDIR="/nix/store/ghzs95qyvdr92d45xx52vfa778qhw908-zsh-5.9/share/zsh/$ZSH_VERSION/help"

# Add plugin directories to PATH and fpath
plugin_dirs=(
  powerlevel10k
)
for plugin_dir in "${plugin_dirs[@]}"; do
  path+="/home/amadeus/.zsh/plugins/$plugin_dir"
  fpath+="/home/amadeus/.zsh/plugins/$plugin_dir"
done
unset plugin_dir plugin_dirs


source /nix/store/21fvi9gafr3bgz8zk9k17d3hzbq46bnv-zsh-autosuggestions-0.7.1/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git history-substring-search)

ZSH_THEME="powerlevel10k"
source $ZSH/oh-my-zsh.sh

# Source plugins
plugins=(
  powerlevel10k/share/zsh-powerlevel10k/powerlevel10k.zsh-theme
)
for plugin in "${plugins[@]}"; do
  [[ -f "/home/amadeus/.zsh/plugins/$plugin" ]] && source "/home/amadeus/.zsh/plugins/$plugin"
done
unset plugin plugins

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="/home/amadeus/.local/share/zsh/history"
mkdir -p "$(dirname "$HISTFILE")"

# Set shell options
set_opts=(
  HIST_FCNTL_LOCK HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY
  NO_APPEND_HISTORY NO_EXTENDED_HISTORY NO_HIST_EXPIRE_DUPS_FIRST
  NO_HIST_FIND_NO_DUPS NO_HIST_IGNORE_ALL_DUPS NO_HIST_SAVE_NO_DUPS
)
for opt in "${set_opts[@]}"; do
  setopt "$opt"
done
unset opt set_opts

alias -- check='sudo nix flake check'
alias -- clean='sudo nix store gc'
alias -- clean-build='sudo nix store gc && sudo nixos-rebuild switch'
alias -- update='sudo nixos-rebuild switch'
source /nix/store/dsc78yzl83s0qjs048dpcf35v3myi6zf-zsh-syntax-highlighting-0.8.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)
source ~/.p10k.zsh
